[manage] FIX: Fatal error when using select from all pages.
This has crept in when I did the refactoring of the query objects.

Fatal error: __clone method called on non-object in /var/www/camp/projects/campaignion-7.x-1.0-beta5/campaignion_manage/lib/SupporterListing.php on line 105